In [13]:
import pandas as pd
import os
# Importing the save_dataframe function from the data_saver module
from data_saver import save_dataframe
from filter_year import filter_by_year_quarter
from filter_range import filter_by_year_range

In [14]:
# Load the CSV file into a DataFrame from the current directory
current_directory = os.getcwd()
Year=2024
Quarter=2
file_name_vehicle_stat = f"BECar_Stat_UK_Registered_{Year}Q{Quarter}_Cleaned.csv"
file_name_vehicle_spec="EV Database\EV_Specifications_UK_full_last_release.csv"
#file_name_EV_Lookup_Tabel = "EV_Lookup_Table.csv"

# Construct the full file path
file_path_vehicle_stat = os.path.join(current_directory, file_name_vehicle_stat)
file_path_vehicle_spec = os.path.join(current_directory, file_name_vehicle_spec)
#file_path_EV_Lookup_Tabel = os.path.join(current_directory, file_name_EV_Lookup_Tabel)

df_vehicle_stats = pd.read_csv(file_path_vehicle_stat)
df_vehicle_stats

       Make     GenModel                           Model   No.
0    ABARTH   ABARTH 500                            500E    68
1    ABARTH   ABARTH 500             500E SCORPIONISSIMA   111
2    ABARTH   ABARTH 500                    500E TURISMO   138
3      AUDI  AUDI E-TRON               E-TRON 55 QUATTRO  1337
4      AUDI  AUDI E-TRON    E-TRON BLACK EDITION 50 QUAT  1119
..      ...          ...                             ...   ...
758   VOLVO   VOLVO XC40   XC40 PRO RECHARGE TWIN EV AWD   471
759   VOLVO   VOLVO XC40            XC40 R-DESIGN P8 AWD    88
760   VOLVO   VOLVO XC40       XC40 RECHARGE TWIN EV AWD   353
761   VOLVO   VOLVO XC40       XC40 ULTIMATE RECHARGE EV  1796
762   VOLVO   VOLVO XC40  XC40 ULTMTE RCHRGE TWIN EV AWD  2337

[763 rows x 4 columns]

In [15]:
df_vehicle_stats["Make Model"] = df_vehicle_stats["Make"] + " " + df_vehicle_stats["Model"]

In [16]:
df_vehicle_stats

,Make,GenModel,Model,No.,Make Model
0,ABARTH,ABARTH 500,500E,68,ABARTH 500E
1,ABARTH,ABARTH 500,500E SCORPIONISSIMA,111,ABARTH 500E SCORPIONISSIMA
2,ABARTH,ABARTH 500,500E TURISMO,138,ABARTH 500E TURISMO
3,AUDI,AUDI E-TRON,E-TRON 55 QUATTRO,1337,AUDI E-TRON 55 QUATTRO
4,AUDI,AUDI E-TRON,E-TRON BLACK EDITION 50 QUAT,1119,AUDI E-TRON BLACK EDITION 50 QUAT
...,...,...,...,...,...
758,VOLVO,VOLVO XC40,XC40 PRO RECHARGE TWIN EV AWD,471,VOLVO XC40 PRO RECHARGE TWIN EV AWD
759,VOLVO,VOLVO XC40,XC40 R-DESIGN P8 AWD,88,VOLVO XC40 R-DESIGN P8 AWD
760,VOLVO,VOLVO XC40,XC40 RECHARGE TWIN EV AWD,353,VOLVO XC40 RECHARGE TWIN EV AWD
761,VOLVO,VOLVO XC40,XC40 ULTIMATE RECHARGE EV,1796,VOLVO XC40 ULTIMATE RECHARGE EV
762,VOLVO,VOLVO XC40,XC40 ULTMTE RCHRGE TWIN EV AWD,2337,VOLVO XC40 ULTMTE RCHRGE TWIN EV AWD

In [17]:
df_vehicle_spec = pd.read_csv(file_path_vehicle_spec)
df_vehicle_spec

,index,Index EV CSH,Index EV,EV Full Name,Market Status,EV Company,EV Model,Usable Battery(kWh),Price per km of range,0-100 sec,...,Date Available,Data Source,EV ID,Link EV Page,Link EV Image,EV Price DE,EV Price NL,EV Price UK,not-unique,processed_dates
0,342,343,343,Abarth 500e Convertible,Current,Abarth,500e Convertible,37.8,186,7.0,...,May-23,1.682899e+09,1904,https://ev-database.org/car/1904/Abarth-500e-C...,https://ev-database.org/img/auto/Abarth_500e_C...,"40,990","41,490","37,195",False,23/05/01
1,275,276,276,Abarth 500e Hatchback,Current,Abarth,500e Hatchback,37.8,172,7.0,...,May-23,1.682899e+09,1903,https://ev-database.org/car/1903/Abarth-500e-H...,https://ev-database.org/img/auto/Abarth_500e_H...,"37,990","38,490","34,195",False,23/05/01
2,641,642,292,Abarth 500e Scorpionissima,Second Hand,Abarth,500e Scorpionissima,37.8,195,7.0,...,January 2023 - April 2023,1.672531e+09,1790,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"43,000","44,000","38,695",False,23/01/01
3,113,114,114,Alfa Romeo Junior Elettrica 54 kWh,Current,Alfa Romeo,Junior Elettrica 54 kWh,50.8,129,9.0,...,Jun-24,1.717200e+09,2184,https://ev-database.org/car/2184/Alfa-Romeo-Ju...,https://ev-database.org/img/auto/Alfa_Romeo_Mi...,"39,500","41,000","36,000",False,24/06/01
4,93,94,94,Alfa Romeo Junior Elettrica 54 kWh Veloce,Current,Alfa Romeo,Junior Elettrica 54 kWh Veloce,50.8,154,7.0,...,Jun-24,1.717200e+09,2185,https://ev-database.org/car/2185/Alfa-Romeo-Ju...,https://ev-database.org/img/auto/Alfa_Romeo_Mi...,"46,000","47,000","42,000",False,24/06/01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,558,559,209,Volvo XC40 P8 AWD Recharge,Second Hand,Volvo,XC40 P8 AWD Recharge,75.0,173,4.9,...,February 2020 - February 2021,1.580515e+09,1188,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"60,437","55,495","49,950",False,20/02/01
392,563,564,214,Volvo XC40 Recharge Pure Electric,Second Hand,Volvo,XC40 Recharge Pure Electric,67.0,146,7.4,...,February 2022 - December 2022,1.643674e+09,1592,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"45,080","46,995","45,750",True,22/02/01
393,548,549,199,Volvo XC40 Recharge Single Motor,Second Hand,Volvo,XC40 Recharge Single Motor,66.0,144,7.3,...,December 2022 - March 2024,1.669853e+09,1796,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"47,500","45,995","46,505",False,22/12/01
394,490,491,141,Volvo XC40 Recharge Twin Motor,Second Hand,Volvo,XC40 Recharge Twin Motor,79.0,155,4.8,...,December 2022 - March 2024,1.669853e+09,1798,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"59,950","59,995","51,755",False,22/12/01
395,534,535,185,Volvo XC40 Recharge Twin Pure Electric,Second Hand,Volvo,XC40 Recharge Twin Pure Electric,75.0,171,4.9,...,February 2022 - December 2022,1.643674e+09,1593,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"56,150","57,495","57,000",True,22/02/01

In [20]:
# Create the "name_match" column in df_vehicle_stats
df_vehicle_stats["name_match"] = df_vehicle_stats["Make Model"].str.lower().isin(df_vehicle_spec["EV Full Name"].str.lower())
df_vehicle_stats

,Make,GenModel,Model,No.,Make Model,name_match
0,ABARTH,ABARTH 500,500E,68,ABARTH 500E,False
1,ABARTH,ABARTH 500,500E SCORPIONISSIMA,111,ABARTH 500E SCORPIONISSIMA,True
2,ABARTH,ABARTH 500,500E TURISMO,138,ABARTH 500E TURISMO,False
3,AUDI,AUDI E-TRON,E-TRON 55 QUATTRO,1337,AUDI E-TRON 55 QUATTRO,True
4,AUDI,AUDI E-TRON,E-TRON BLACK EDITION 50 QUAT,1119,AUDI E-TRON BLACK EDITION 50 QUAT,False
...,...,...,...,...,...,...
758,VOLVO,VOLVO XC40,XC40 PRO RECHARGE TWIN EV AWD,471,VOLVO XC40 PRO RECHARGE TWIN EV AWD,False
759,VOLVO,VOLVO XC40,XC40 R-DESIGN P8 AWD,88,VOLVO XC40 R-DESIGN P8 AWD,False
760,VOLVO,VOLVO XC40,XC40 RECHARGE TWIN EV AWD,353,VOLVO XC40 RECHARGE TWIN EV AWD,False
761,VOLVO,VOLVO XC40,XC40 ULTIMATE RECHARGE EV,1796,VOLVO XC40 ULTIMATE RECHARGE EV,False
762,VOLVO,VOLVO XC40,XC40 ULTMTE RCHRGE TWIN EV AWD,2337,VOLVO XC40 ULTMTE RCHRGE TWIN EV AWD,False

In [21]:
df = pd.concat([df_vehicle_stats, df_vehicle_spec])
df

,Make,GenModel,Model,No.,Make Model,name_match,index,Index EV CSH,Index EV,EV Full Name,...,Date Available,Data Source,EV ID,Link EV Page,Link EV Image,EV Price DE,EV Price NL,EV Price UK,not-unique,processed_dates
0,ABARTH,ABARTH 500,500E,68.0,ABARTH 500E,False,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABARTH,ABARTH 500,500E SCORPIONISSIMA,111.0,ABARTH 500E SCORPIONISSIMA,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABARTH,ABARTH 500,500E TURISMO,138.0,ABARTH 500E TURISMO,False,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AUDI,AUDI E-TRON,E-TRON 55 QUATTRO,1337.0,AUDI E-TRON 55 QUATTRO,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AUDI,AUDI E-TRON,E-TRON BLACK EDITION 50 QUAT,1119.0,AUDI E-TRON BLACK EDITION 50 QUAT,False,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,NaN,NaN,NaN,NaN,NaN,558.0,559.0,209.0,Volvo XC40 P8 AWD Recharge,...,February 2020 - February 2021,1.580515e+09,1188.0,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"60,437","55,495","49,950",False,20/02/01
392,NaN,NaN,NaN,NaN,NaN,NaN,563.0,564.0,214.0,Volvo XC40 Recharge Pure Electric,...,February 2022 - December 2022,1.643674e+09,1592.0,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"45,080","46,995","45,750",True,22/02/01
393,NaN,NaN,NaN,NaN,NaN,NaN,548.0,549.0,199.0,Volvo XC40 Recharge Single Motor,...,December 2022 - March 2024,1.669853e+09,1796.0,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"47,500","45,995","46,505",False,22/12/01
394,NaN,NaN,NaN,NaN,NaN,NaN,490.0,491.0,141.0,Volvo XC40 Recharge Twin Motor,...,December 2022 - March 2024,1.669853e+09,1798.0,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"59,950","59,995","51,755",False,22/12/01
395,NaN,NaN,NaN,NaN,NaN,NaN,534.0,535.0,185.0,Volvo XC40 Recharge Twin Pure Electric,...,February 2022 - December 2022,1.643674e+09,1593.0,https://ev-database.org/compare/second-hand-us...,https://ev-database.org/compare/second-hand-us...,"56,150","57,495","57,000",True,22/02/01